# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

c_dghst <- function(x, mu, sigma, skew, shape, logr) {
    .Call(`_tsdistributions_c_dghst`, x, mu, sigma, skew, shape, logr)
}

c_rghst <- function(n, mu, sigma, skew, shape) {
    .Call(`_tsdistributions_c_rghst`, n, mu, sigma, skew, shape)
}

c_dghyp <- function(x, alpha, beta, delta, mu, lambda, logr) {
    .Call(`_tsdistributions_c_dghyp`, x, alpha, beta, delta, mu, lambda, logr)
}

c_dgh <- function(x, mu, sigma, skew, shape, lambda, logr) {
    .Call(`_tsdistributions_c_dgh`, x, mu, sigma, skew, shape, lambda, logr)
}

c_dnig <- function(x, mu, sigma, skew, shape, logr) {
    .Call(`_tsdistributions_c_dnig`, x, mu, sigma, skew, shape, logr)
}

c_rstd <- function(n, mu, sigma, shape) {
    .Call(`_tsdistributions_c_rstd`, n, mu, sigma, shape)
}

c_dstd <- function(x, mu, sigma, shape, logr) {
    .Call(`_tsdistributions_c_dstd`, x, mu, sigma, shape, logr)
}

c_pstd <- function(q, mu, sigma, shape) {
    .Call(`_tsdistributions_c_pstd`, q, mu, sigma, shape)
}

c_qstd <- function(p, mu, sigma, shape) {
    .Call(`_tsdistributions_c_qstd`, p, mu, sigma, shape)
}

c_rsstd <- function(n, mu, sigma, skew, shape) {
    .Call(`_tsdistributions_c_rsstd`, n, mu, sigma, skew, shape)
}

c_dsstd <- function(x, mu, sigma, skew, shape, logr) {
    .Call(`_tsdistributions_c_dsstd`, x, mu, sigma, skew, shape, logr)
}

c_psstd <- function(q, mu, sigma, skew, shape) {
    .Call(`_tsdistributions_c_psstd`, q, mu, sigma, skew, shape)
}

c_qsstd <- function(p, mu, sigma, skew, shape) {
    .Call(`_tsdistributions_c_qsstd`, p, mu, sigma, skew, shape)
}

c_djsu <- function(x, mu, sigma, skew, shape, logr) {
    .Call(`_tsdistributions_c_djsu`, x, mu, sigma, skew, shape, logr)
}

c_qjsu <- function(p, mu, sigma, skew, shape) {
    .Call(`_tsdistributions_c_qjsu`, p, mu, sigma, skew, shape)
}

c_pjsu <- function(q, mu, sigma, skew, shape) {
    .Call(`_tsdistributions_c_pjsu`, q, mu, sigma, skew, shape)
}

c_rjsu <- function(n, mu, sigma, skew, shape) {
    .Call(`_tsdistributions_c_rjsu`, n, mu, sigma, skew, shape)
}

c_rsnorm <- function(n, mu, sigma, skew) {
    .Call(`_tsdistributions_c_rsnorm`, n, mu, sigma, skew)
}

c_dsnorm <- function(x, mu, sigma, skew, logr) {
    .Call(`_tsdistributions_c_dsnorm`, x, mu, sigma, skew, logr)
}

c_psnorm <- function(q, mu, sigma, skew) {
    .Call(`_tsdistributions_c_psnorm`, q, mu, sigma, skew)
}

c_qsnorm <- function(p, mu, sigma, skew) {
    .Call(`_tsdistributions_c_qsnorm`, p, mu, sigma, skew)
}

c_rged <- function(n, mu, sigma, shape) {
    .Call(`_tsdistributions_c_rged`, n, mu, sigma, shape)
}

c_dged <- function(x, mu, sigma, shape, logr) {
    .Call(`_tsdistributions_c_dged`, x, mu, sigma, shape, logr)
}

c_pged <- function(q, mu, sigma, shape) {
    .Call(`_tsdistributions_c_pged`, q, mu, sigma, shape)
}

c_qged <- function(p, mu, sigma, shape) {
    .Call(`_tsdistributions_c_qged`, p, mu, sigma, shape)
}

c_rsged <- function(n, mu, sigma, skew, shape) {
    .Call(`_tsdistributions_c_rsged`, n, mu, sigma, skew, shape)
}

c_dsged <- function(x, mu, sigma, skew, shape, logr) {
    .Call(`_tsdistributions_c_dsged`, x, mu, sigma, skew, shape, logr)
}

c_psged <- function(q, mu, sigma, skew, shape) {
    .Call(`_tsdistributions_c_psged`, q, mu, sigma, skew, shape)
}

c_qsged <- function(p, mu, sigma, skew, shape) {
    .Call(`_tsdistributions_c_qsged`, p, mu, sigma, skew, shape)
}

c_dhyp <- function(x, mu, sigma, skew, shape, logr) {
    .Call(`_tsdistributions_c_dhyp`, x, mu, sigma, skew, shape, logr)
}

c_rghyp <- function(n, mu = 0, delta = 1, alpha = 1, beta = 0, lambda = 1) {
    .Call(`_tsdistributions_c_rghyp`, n, mu, delta, alpha, beta, lambda)
}

